### ISSUE TITLE
Add ability to set commit status name in put step

### ISSUE THREAD

**Issue by matthewthomasoc** [samcontesse/gitlab-merge-request-resource#105]
I want to use instance vars combined with pipeline groups. For example, a merge check pipeline that has multiple different merge checks running in parallel, grouped for organization, and instance vars for each merge check for separate branches. I want these merge checks to add their own individual commit status updates to the merge request, without needing to define multiple merge-request resources pointing to the same repository and overwriting `BUILD_PIPELINE_NAME` using the `pipeline_name` parameter. This gets very messy when you have 3+ merge checks. It would be much cleaner if there was an optional parameter on the `put` step that overwrote `BUILD_PIPELINE_NAME`.

```yml
- put: my-repository
  params:
    repository: my-repository
    name: my-commit-status-name
    status: running
```
