### ISSUE TITLE
Support for stages?

### ISSUE THREAD

**Issue by ChrisJBurns** [samcontesse/gitlab-merge-request-resource#135]
Currently if I have two separate jobs in concourse, one for unit tests and another for integration tests, there is no way of getting Gitlab to link to both of these jobs. It only ever links to the latest one that sends a status to it.

```yaml
  - name: mr-integ-tests
    max_in_flight: 10
    plan:
      # task gets the source code from the repository
      - in_parallel:
          - get: source-code
            resource: merge-request
            passed: [ "mr-unit-tests" ]
            trigger: true
            on_success:
              put: merge-request
              params:
                repository: source-code
                status: running
```

Could we add `stage` ? So then the pipelines are built in gitlab based on the data we send it from the merge request pipeline.

Example:
![image](https://user-images.githubusercontent.com/29541485/236317893-67e08f9f-3f8b-46e3-84c9-adfd8cd47cb6.png)

Could be something like:

```yaml
  - name: build
    max_in_flight: 10
    plan:
      # task gets the source code from the repository
      - in_parallel:
          - get: source-code
            resource: merge-request
            trigger: true
            on_success:
              put: merge-request
              params:
                repository: source-code
                status: running
                stage: build

  - name: test1
    max_in_flight: 10
    plan:
      # task gets the source code from the repository
      - in_parallel:
          - get: source-code
            resource: merge-request
            trigger: true
            on_success:
              put: merge-request
              params:
                repository: source-code
                status: running
                stage: test1
```

or something like that. as at the moment, we have many concurrent pipelines but there is no way to link them to a MR in Gitlab for each of the jobs that are run as part of that pipeline.
