### ISSUE TITLE
Set commit status failed: 400, response 

### ISSUE THREAD

**Issue by samarara** [samcontesse/gitlab-merge-request-resource#26]
When setting the status as running the put step returns 
```
Set commit status failed: 400, response
```

Any idea why this is? The api access token have all the scopes. 

pipeline: 
```yml
resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: ((mr-resource-uri))

resources:
  - name: enrolment-application-mr
    type: merge-request
    source:
      uri: ((enrolment-app-uri))
      branch: chore/ci
      private_token: ((enrolment-react-access-token))
      target_branch: dev
      skip_work_in_progress: true

jobs:
  - name: run-tests
    public: true
    plan:
      - get: enrolment-application-mr
        trigger: true
      - put: enrolment-application-mr
        params:
          repository: enrolment-application-mr
          status: running
      - task: run-unit-tests
        config:
          platform: linux
          inputs:
            - name: enrolment-application-mr
          image_resource:
            type: docker-image
            source:
              repository: ((devops-utils-image-uri))
          run:
            path: bash
            args:
            - -exc
            - |
              export SKIP_PREFLIGHT_CHECK=true
              pwd
              ls -la
              cd enrolment-application-mr
              npm i
              npx lerna bootstrap --hoist
              npm run test
        on_failure:
          put: enrolment-application-mr
          params:
            repository: enrolment-application-mr
            status: failed
            labels: ['unit-test', 'stage']
            comment:
              text: UNIT TESTS FAILED! Save the world, write tests!
        on_success:
          put: enrolment-application-mr
          params:
            repository: enrolment-application-mr
            status: success
            labels: ['unit-test', 'stage']
            comment:
              file: out/commt.txt
              text: |
                Add new comment.
                $FILE_CONTENT
```
