### ISSUE TITLE
Skip ssl validation 

### ISSUE THREAD

**Issue by gucarreira** [samcontesse/gitlab-merge-request-resource#3]
There is a parameter to skip resource to check ssl certificate, because we use a self sign-in certificate in our gitlab installation.
We build an image using your repository or if we import self sign-in din S.O. container during build go can understand a certificate and skip ssl validation doesn't matter.
Thanks for help

**Comment by samcontesse** [comment]
Hello Gustavo,

I just created #4 that adds an `insecure` source option. Can configure your pipeline to use this image :
```
source:
    repository: samcontesse/gitlab-merge-request-resource
    tag: feature_skip-ssl
```

 And set `insecure: true` in your source ?

```
resources:
- name: merge-request
  type: merge-request
  source:
    uri: https://my-insecure-server.domain.com/myname/myproject.git
    private_token: XXX
    insecure: true
```

Can you test and check it works for you ?
