### ISSUE TITLE
Check succeeds using private access token, but clone returns 403

### ISSUE THREAD

**Issue by QuinnStevens** [samcontesse/gitlab-merge-request-resource#31]
I'm just trying to set up a PoC project to see how this resource works, and I've set up the resource as suggested in the readme. I'm getting the access token from a k8s secret.

The resource itself seems to work fine. It checks successfully and triggers the job. However, when the job actually starts (atm it's just a bare-bones task which prints hello world, nothing fancy), it fails with `fatal: unable to access 'https://gitlab-ci-token:((redacted))@gitlab.company.com/path/to/repo.git/': The requested URL returned error: 403`

the mr resource yaml is:
```yaml
resources:
- name: merge-request-src
  icon: git
  type: merge-request
  source:
    uri: https://gitlab.company.com/path/to/repo.git
    private_token: ((gitlab.access_token))
```
