### ISSUE TITLE
Support ssh URLs for private repositories

### ISSUE THREAD

**Issue by dschulten** [samcontesse/gitlab-merge-request-resource#45]
Our repositories are usually private and require ssh keys.

I was only able to make the `get: merge-request` build step work after I made my repository public and used the https:// URL of my repository.

Can we please have support for git: urls that must use ssh keys? Sth like:

```
resources:
  - name: merge-request
    type: merge-request
    source:
      uri: git@git.dev.example.com:foo/bar/myproject.git
      private_key: ((user.private_key))
      private_token: ((user.gitlab_personal_accesss_token))
      insecure: true
```
