### ISSUE TITLE
Internal Gitlab Problem; failure to resolve host name

### ISSUE THREAD

**Issue by thepunknerd** [samcontesse/gitlab-merge-request-resource#66]
I'm trying to follow the example code with an internally hosted gitlab instance. 

Here is my pipeline definition (sanitized)  

```yaml
resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: samcontesse/gitlab-merge-request-resource

resources:
- name: merge-request
  type: merge-request
  source:
    uri: https://gitlab.myco.int/terraform/proof-of-concepts/terraform-pipelines.git
    private_token: <private_token>

jobs:
- name: sample-merge-request
  plan:
  - get: merge-request
    trigger: true
  - put: merge-request
    params:
      repository: merge-request
      status: running
  - task: unit-test
    file: merge-request/ci/tasks/unit-test.yml
  on_failure:
    put: merge-request
    params:
      repository: merge-request
      status: failed
  on_success:
    put: merge-request
    params:
      repository: merge-request
      status: success
      labels: ['unit-test', 'stage']
      comment:
        file: out/commt.txt
        text: |
          Add new comment.
          $FILE_CONTENT
```

I'm seeing this error message:

`error running command: Get "https://gitlab.myco.int/api/v4/projects/terraform%2Fproof-of-concepts%2Fterraform-pipelines/merge_requests?labels=&order_by=updated_at&sort=asc&source_branch=&state=opened&target_branch=": dial tcp: lookup gitlab.myco.int on 8.8.8.8:53: no such host`

It seems like it is trying to resolve my internal url with Google's dns. Any ideas?
