### ISSUE TITLE
Wrong status update on MR merged

### ISSUE THREAD

**Issue by gucarreira** [samcontesse/gitlab-merge-request-resource#8]
Hello Samuel,

I realized that when the repository is without MR the component is waiting for new MR to trigger job.
After the MR is created the component releases the pipeline
But when the MR is accepted and the repository has no MR open and a job is started the component update status on MR that has already been accepted.

I'm using 
```
  - name: merge-request
    type: docker-image
    source:
      repository: samcontesse/gitlab-merge-request-resource
      # tag: feature_skip-ssl
      tag: bugfix_failed-merge-commit-status
```

But both tags occurs the same problem.
If you need more information let me know

Thanks for help

Gustavo

**Comment by samcontesse** [comment]
Hi Gustavo,

In our repository, we use the option **Only allow merge requests to be merged if the pipeline succeeds** which will ensure the build has passed before the MR can be merged. In other words, we do not have this problem. A `[skip ci]` can be added to your commit message in order to bypass the build (eg. changes that do not need a build, like updating the changelog, ...).

If you can't use this option, I can consider adding a status check before updating the commit status. Let me know what fits you best.

**Comment by gucarreira** [comment]
Hi Samuel,

I hope that the problem is in the process of updating the merge request after the pipeline is executed for the first time.
Steps to reproduce

1. Close or merge all MRs
![image](https://user-images.githubusercontent.com/26637254/44163355-8a910380-a099-11e8-987b-6c1560fb6f40.png)
1. Destroy Pipeline
1. Create Pipeline and trigger the job. After that job is waiting to open a merge request.
![image](https://user-images.githubusercontent.com/26637254/44163462-e78cb980-a099-11e8-9f4a-add0fbeacbc6.png)
1. The parameters are working as well. The pipeline is waiting for resolve WIP.
![image](https://user-images.githubusercontent.com/26637254/44164884-a0082c80-a09d-11e8-9474-0dc9b0fc48f5.png)
![image](https://user-images.githubusercontent.com/26637254/44164907-b7471a00-a09d-11e8-8ba0-7415604d35a8.png)
![image](https://user-images.githubusercontent.com/26637254/44165188-68e64b00-a09e-11e8-8cd3-9cb507c25742.png)

**For whatever reason my pipeline failed and my DEV change merge request to WIP**

1. Gitlab WIP Merge Request
![image](https://user-images.githubusercontent.com/26637254/44165987-9502cb80-a0a0-11e8-8a15-c59863b7dac6.png)
1. If I trigger the job again, merge request component doesn't change to new version to put pipeline in wait status.
![image](https://user-images.githubusercontent.com/26637254/44166180-1d816c00-a0a1-11e8-96c5-ff52494bdc43.png)
![image](https://user-images.githubusercontent.com/26637254/44166231-38ec7700-a0a1-11e8-9697-344d1bfd3d0c.png)

I suppose that check module doesn't change MR number 6 to new status or I close MR 6 and open a new MR with WIP pipeline doens't wait to resolve WIP

**Comment by samcontesse** [comment]
Hello @gucarreira,

Do you have the same commit sha in 5 and 6 ?

Note: if you trigger builds manually, Concourse will always pick up the last emitted version - no matter if they are WIP or not mergeable because the `in` script is only here to checkout the repository. 

Do you always trigger build manually ?

**Comment by gucarreira** [comment]
Hi, Samuel

I'm using same commit sha, but I did some tests and the behavior remained the same.
But I didn't know the behavior of the concourse. I already suspected.
My developers are new to this concept and the build is being manual.

But I was discussing with friend https://gitlab.com/axpira and he gave an idea, I was so focused on solving the problem trying to fix the resource, I put a check merge request as a task.

Below some fragments of the solution used

```yaml
  - task: check-merge-request
    file: pipeline-code/tasks/check_mr.yml
    input_mapping:
      repo-mergerequest: repo-mr
    params:
      DEBUG: ((debug))
      GITLAB_TOKEN: ((gitlab-token))
      GITLAB_API_URL: ((gitlab-api-url))
```

[check_mr.zip](https://github.com/samcontesse/gitlab-merge-request-resource/files/2346002/check_mr.zip)


@samcontesse Very thank you for your time and help
